spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:23306/simple-board?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: simple-board

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: false
        default_batch_fetch_size: 100
    open-in-view: false

  logging:
    config: classpath:log4j2-spring.xml

server:
  port: 8081

jwt:
  secret: verySecretKeyForJWTAuthorizationSimpleBoardProject
